 
spring:

    datasource:
            url: jdbc:mysql://localhost:3306/Student
            driver-class-name: com.mysql.cj.jdbc.Driver
            username: root
            password: root
   
 
   
   
    jpa:
      hibernate:
        ddl-auto: update 
        
      show-sql: true
      
      database-platform: org.hibernate.dialect.MySQLDialect
      
      
      
    
      
    application:
         name: College
         
server:
  port: 8080
     
      
 
